// src/theme/debug.ts

import { backup } from "node:sqlite";
import type { ThemeColors } from "../generated/theme-colors.js";
import { semantic } from "../semantic.js";

export const mapColors = {
    	"minimap.background": semantic.background,
        "minimap.errorHighlight": semantic.error,
		"minimap.chatEditHighlight": semantic.info,
        "minimap.findMatchHighlight": semantic.accent,
        "minimap.foregroundOpacity": semantic.hover,
		"minimap.infoHighlight": semantic.info,
		"minimap.selectionHighlight": semantic.accent, 
		"minimap.selectionOccurrenceHighlight": semantic.info,
		"minimap.warningHighlight": semantic.warning,
		"minimapGutter.addedBackground": semantic.added,
		"minimapGutter.deletedBackground": semantic.deleted,
		"minimapGutter.modifiedBackground": semantic.modified,
		"minimapSlider.activeBackground": semantic.active,
		"minimapSlider.background": semantic.slider,
		"minimapSlider.hoverBackground": semantic.hover,
        "editorGutter.addedBackground": semantic.added,
		"editorGutter.addedSecondaryBackground": semantic.added,
		"editorGutter.background": semantic.background,
		"editorGutter.commentDraftGlyphForeground": semantic.syntax.comment,
		"editorGutter.commentGlyphForeground": semantic.syntax.comment,
		"editorGutter.commentRangeForeground": semantic.syntax.comment,
		"editorGutter.commentUnresolvedGlyphForeground": semantic.syntax.comment,
		"editorGutter.deletedBackground": semantic.deleted,
		"editorGutter.deletedSecondaryBackground": semantic.deleted,
		"editorGutter.foldingControlForeground": semantic.disabled,
		"editorGutter.itemBackground": semantic.info,
		"editorGutter.itemGlyphForeground": semantic.info,
		"editorGutter.modifiedBackground": semantic.modified,
		"editorGutter.modifiedSecondaryBackground": semantic.modified,
        "scrollbar.background": semantic.background,
        "scrollbarSlider.background": semantic.slider,
        "scrollbarSlider.hoverBackground": semantic.hover,
        "gauge.errorForeground": semantic.error,
        "gauge.background": semantic.background,
        "editorOverviewRuler.addedForeground": semantic.added,
		"editorOverviewRuler.background": semantic.background,
		"editorOverviewRuler.border": semantic.zero,
		"editorOverviewRuler.bracketMatchForeground": semantic.match,
		"editorOverviewRuler.commentDraftForeground": semantic.syntax.comment,
		"editorOverviewRuler.commentForeground": semantic.syntax.comment,
		"editorOverviewRuler.commentUnresolvedForeground": semantic.syntax.comment,
		"editorOverviewRuler.commonContentForeground": semantic.foreground,
		"editorOverviewRuler.currentContentForeground": semantic.foreground,
		"editorOverviewRuler.deletedForeground": semantic.deleted,
		"editorOverviewRuler.errorForeground": semantic.error,
		"editorOverviewRuler.findMatchForeground": semantic.match,
		"editorOverviewRuler.incomingContentForeground": semantic.new,
		"editorOverviewRuler.infoForeground": semantic.info,
		"editorOverviewRuler.inlineChatInserted": semantic.added,
		"editorOverviewRuler.inlineChatRemoved": semantic.deleted,
		"editorOverviewRuler.modifiedForeground": semantic.modified,
		"editorOverviewRuler.rangeHighlightForeground": semantic.highlight,
		"editorOverviewRuler.selectionHighlightForeground": semantic.focus,
		"editorOverviewRuler.warningForeground": semantic.warning,
		"editorOverviewRuler.wordHighlightForeground": semantic.highlight,
		"editorOverviewRuler.wordHighlightStrongForeground": semantic.accent,
		"editorOverviewRuler.wordHighlightTextForeground": semantic.accent,
} satisfies ThemeColors;
