import { palette } from "../palette.js";
import { alpha } from "./color.js"

export const semantic = {
    zero: palette.fund.zero,
    accent: palette.light[4]!,
    active: palette.gray[19]!,
    added: alpha(palette.city.t, 0.3),
    background: palette.gray[2]!,
    backgroundTransparent: alpha(palette.gray[6]!, 0.5),
    breakpoint: palette.light[8]!,
    border: palette.light[3]!,
    button: palette.light[4]!,
    candidate: palette.gray[14]!,
    deleted: alpha(palette.gray[7]!, 0.5),
    disabled: palette.gray[5]!,
    drop: palette.light[4]!,
    dropdown: palette.light[1]!,
    error: palette.light[5]!,
    focus: alpha(palette.gray[19]!, 0.1),
    foreground: palette.gray[18]!,
    foregroundTransparent: alpha(palette.gray[19]!, 0.8),
    highlight: alpha(palette.gray[5]!, 0.5),
    hover: alpha(palette.gray[8]!, 0.3),
    inactive: palette.gray[10]!,
    info: palette.light[7]!,
    input: alpha(palette.gray[8]!, 0.4),
    link: palette.light[7]!,
    local: palette.city.t,
    match: alpha(palette.light[8]!, 0.3),
    modified: alpha(palette.light[6]!, 0.8),
    new: palette.city.t,
    old: palette.city.k,
    placeholder: palette.gray[13]!,
    remote: palette.gray[10]!,
    separator: palette.gray[15]!,
    shadow: alpha(palette.gray[4]!, 0.3),
    slider: alpha(palette.light[4]!, 0.3),
    sticky: palette.gray[2]!,
    success: palette.light[3]!,
    symbolIcon: palette.gray[16]!,
    untracked: palette.gray[19]!,
    warning: palette.light[7]!,
    widget: palette.gray[1]!,
    terminal: {
        background: palette.gray[2]!,
    },
    ansi: {
        normal: {
            black: palette.black,
            white: palette.white,
            blue: palette.city.k,
            cyan: palette.blue[0]!,
            green: palette.blue[1]!,
            magenta: palette.blue[2]!,
            red: palette.blue[3]!,
            yellow: palette.blue[4]!,
        },
        bright: {
            black: palette.gray[7]!,
            white: palette.gray[2]!,
            blue: palette.city.t,
            cyan: palette.light[0]!,
            green: palette.light[1]!,
            magenta: palette.light[2]!,
            red: palette.light[3]!,
            yellow: palette.light[4]!,
        }
    },
    syntax: {
        attribute: palette.white,
        class: palette.light[5]!,
        comment: palette.blue[9]!,
        constant: palette.blue[2]!,
        decorator: palette.light[2]!,
        enumMember: palette.light[5]!,
        escape: palette.light[1]!,
        fenced: palette.gray[16]!,
        function: palette.light[3]!,
        heading: palette.light[5]!,
        interface: palette.light[5]!,
        invalid: palette.light[5]!,
        keyword: palette.blue[5]!,
        number: palette.light[2]!,
        operator: palette.light[5]!,
        parameter: palette.primary.foreground,
        property: palette.primary.foreground,
        punctuation: palette.gray[17]!,
        regexp: palette.light[10]!,
        string: palette.gray[19]!,
        tag: palette.light[2]!,
        type: palette.light[5]!,
        variable: palette.primary.foreground,
    },
    order: palette.light,
} as const;
