import { palette } from "../palette.js";
import { alpha } from "./color.js"
import { hexFromArgb } from "@material/material-color-utilities";


export const semantic = {
    zero: palette.zero,
    accent: hexFromArgb(palette.primary.tone(70)),
    active: hexFromArgb(palette.neutral.tone(100)),
    added: palette.city.t,
    addedTransparent: alpha(hexFromArgb(palette.primary.tone(50)), 0.2),
    background: palette.black,
    backgroundTransparent: alpha(palette.black, 0.8),
    breakpoint: hexFromArgb(palette.primary.tone(70)),
    border: hexFromArgb(palette.neutral.tone(30)),
    button: hexFromArgb(palette.primary.tone(60)),
    candidate: hexFromArgb(palette.neutral.tone(70)),
    deleted: hexFromArgb(palette.neutral.tone(60)),
    deletedTransparent: alpha(hexFromArgb(palette.neutral.tone(60)), 0.2),
    disabled: hexFromArgb(palette.neutral.tone(50)),
    drop: hexFromArgb(palette.neutral.tone(40)),
    dropdown: hexFromArgb(palette.primary.tone(65)),
    error: hexFromArgb(palette.tertiary.tone(80)),
    focus: alpha(hexFromArgb(palette.neutral.tone(30)), 0.4),
    foreground: palette.white,
    foregroundTransparent: alpha(palette.white, 0.8),
    highlight: alpha(hexFromArgb(palette.neutral.tone(35)), 0.4),
    hover: alpha(hexFromArgb(palette.neutral.tone(60)), 0.2),
    inactive: hexFromArgb(palette.neutral.tone(70)),
    info: hexFromArgb(palette.tertiary.tone(80)),
    input: alpha(hexFromArgb(palette.neutral.tone(60)), 0.2),
    link: hexFromArgb(palette.primary.tone(80)),
    local: palette.city.t,
    match: alpha(hexFromArgb(palette.secondary.tone(60)), 0.2),
    modified: alpha(hexFromArgb(palette.secondary.tone(50)), 0.8),
    new: palette.city.t,
    newTransparent: alpha(palette.city.t, 0.6),
    old: palette.city.k,
    oldTransparent: alpha(palette.city.k, 0.6),
    placeholder: hexFromArgb(palette.neutral.tone(90)),
    remote: hexFromArgb(palette.neutral.tone(20)),
    separator: palette.white,
    shadow: alpha(hexFromArgb(palette.neutral.tone(30)), 0.4),
    slider: alpha(hexFromArgb(palette.primary.tone(90)), 0.5),
    sticky: palette.black,
    success: hexFromArgb(palette.secondary.tone(60)),
    symbolIcon: palette.white,
    untracked: hexFromArgb(palette.neutral.tone(70)),
    warning: hexFromArgb(palette.tertiary.tone(80)),
    widget: palette.black,
    terminal: {
        background: palette.black,
    },
    ansi: {
        normal: {
            black: palette.black,
            white: palette.white,
            blue: hexFromArgb(palette.primary.tone(40)),
            cyan: hexFromArgb(palette.primary.tone(60)),
            green: hexFromArgb(palette.primary.tone(70)),
            magenta: hexFromArgb(palette.primary.tone(75)),
            red: hexFromArgb(palette.primary.tone(78)),
            yellow: hexFromArgb(palette.primary.tone(80)),
        },
        bright: {
            black: hexFromArgb(palette.neutral.tone(80)),
            white: hexFromArgb(palette.neutral.tone(40)),
            blue: hexFromArgb(palette.secondary.tone(40)),
            cyan: hexFromArgb(palette.secondary.tone(60)),
            green: hexFromArgb(palette.secondary.tone(70)),
            magenta: hexFromArgb(palette.secondary.tone(75)),
            red: hexFromArgb(palette.secondary.tone(78)),
            yellow: hexFromArgb(palette.secondary.tone(80)),
        }
    },
    syntax: {
        attribute: palette.white,
        class: hexFromArgb(palette.primary.tone(90)),
        comment: hexFromArgb(palette.primary.tone(80)),
        constant: hexFromArgb(palette.primary.tone(70)),
        decorator: hexFromArgb(palette.primary.tone(60)),
        enumMember: hexFromArgb(palette.secondary.tone(90)),
        escape: hexFromArgb(palette.secondary.tone(80)),
        fenced: hexFromArgb(palette.neutral.tone(80)),
        function: hexFromArgb(palette.secondary.tone(70)),
        heading: hexFromArgb(palette.secondary.tone(60)),
        interface: hexFromArgb(palette.tertiary.tone(90)),
        invalid: hexFromArgb(palette.tertiary.tone(80)),
        keyword: hexFromArgb(palette.tertiary.tone(70)),
        number: hexFromArgb(palette.tertiary.tone(60)),
        operator: palette.white,
        parameter: palette.white,
        property: palette.white,
        punctuation: palette.white,
        regexp: hexFromArgb(palette.neutral.tone(70)),
        string: hexFromArgb(palette.neutral.tone(60)),
        tag: hexFromArgb(palette.primary.tone(80)),
        type: hexFromArgb(palette.primary.tone(70)),
        variable: palette.white,
    },
    order: Array.from(
        { length: 30 },
        (_, i) => hexFromArgb(palette.neutralVariant.tone(i * 3))),
} as const;
