import { palette } from "./palette.js";
import { alpha } from "./color.js"

export const semantic = {
    zero: palette.fund.zero,
    accent: palette.light[14]!,
    active: palette.gray[19]!,
    added: alpha(palette.city.t, 0.3),
    background: palette.gray[2]!,
    backgroundTransparent: alpha(palette.gray[6]!, 0.5),
    breakpoint: palette.blue[7]!,
    border: palette.light[13]!,
    button: palette.dark[5]!,
    candidate: palette.gray[14]!,
    deleted: alpha(palette.gray[7]!, 0.5),
    disabled: palette.gray[5]!,
    drop: palette.light[14]!,
    error: palette.blue[15]!,
    focus: alpha(palette.gray[19]!, 0.1),
    foreground: palette.gray[18]!,
    foregroundTransparent: alpha(palette.gray[19]!, 0.8),
    highlight: alpha(palette.gray[5]!, 0.5),
    hover: alpha(palette.gray[8]!, 0.3),
    inactive: palette.gray[10]!,
    info: palette.light[14]!,
    input: alpha(palette.gray[8]!, 0.4),
    link: palette.blue[17]!,
    local: palette.city.t,
    match: alpha(palette.dark[6]!, 0.3),
    modified: alpha(palette.light[16]!, 0.8),
    new: palette.city.t,
    old: palette.city.k,
    placeholder: palette.gray[13]!,
    remote: palette.gray[10]!,
    separator: palette.gray[15]!,
    shadow: alpha(palette.gray[4]!, 0.3),
    slider: alpha(palette.light[14]!, 0.3),
    sticky: palette.gray[2]!,
    success: palette.blue[13]!,
    symbolIcon: palette.gray[16]!,
    untracked: palette.gray[19]!,
    warning: palette.blue[17]!,
    widget: palette.gray[5]!,
    terminal: {
        background: palette.gray[2]!,
    },
    ansi: {
        black: palette.black,
        white: palette.white,
        blue: palette.city.k,
        cyan: palette.blue[10]!,
        green: palette.blue[11]!,
        magenta: palette.blue[12]!,
        red: palette.blue[13]!,
        yellow: palette.blue[14]!,
        brightBlack: palette.gray[7]!,
        brightWhite: palette.gray[2]!,
        brightBlue: palette.city.t,
        brightCyan: palette.light[10]!,
        brightGreen: palette.light[11]!,
        brightMagenta: palette.light[12]!,
        brightRed: palette.light[13]!,
        brightYellow: palette.light[14]!,
    },
    syntax: {
        attribute: palette.white,
        class: palette.light[15]!,
        comment: palette.blue[9]!,
        constant: palette.blue[7]!,
        decorator: palette.blue[12]!,
        enumMember: palette.light[15]!,
        escape: palette.blue[11]!,
        function: palette.blue[13]!,
        interface: palette.light[15]!,
        invalid: palette.blue[15]!,
        keyword: palette.light[15]!,
        number: palette.blue[9]!,
        operator: palette.light[15]!,
        parameter: palette.primary.foreground,
        property: palette.primary.foreground,
        punctuation: palette.gray[17]!,
        regexp: palette.blue[10]!,
        string: palette.gray[19]!,
        tag: palette.blue[12]!,
        type: palette.light[15]!,
        variable: palette.primary.foreground,
    },
    order: palette.blue.slice(-10)
} as const;
