import { semantic } from "./semantic.js";
import convert from 'color-convert';

export const config = {
    colors: {
        background_tab: convert.hex.rgb(semantic.background),
        background_tab_inactive: convert.hex.rgb(semantic.background),
        bookmark_text: convert.hex.rgb(semantic.text),
        button_background: convert.hex.rgb(semantic.button),
        control_background: convert.hex.rgb(semantic.control),
        frame_inactive: convert.hex.rgb(semantic.inactive),
        frame_incognito_inactive: convert.hex.rgb(semantic.inactive),
        frame_incognito: convert.hex.rgb(semantic.background),
        frame: convert.hex.rgb(semantic.background),
        ntp_background: convert.hex.rgb(semantic.background),
        ntp_header: convert.hex.rgb(semantic.header),
        ntp_link: convert.hex.rgb(semantic.link),
        ntp_text: convert.hex.rgb(semantic.text),
        omnibox_background: convert.hex.rgb(semantic.omnibox),
        omnibox_results_background: convert.hex.rgb(semantic.omnibox),
        omnibox_results_text_selected: convert.hex.rgb(semantic.selected),
        omnibox_results_text: convert.hex.rgb(semantic.result),
        omnibox_results_url_selected: convert.hex.rgb(semantic.selected),
        omnibox_results_url: convert.hex.rgb(semantic.url),
        omnibox_text: convert.hex.rgb(semantic.text),
        popup_border: convert.hex.rgb(semantic.border),
        popup_highlight_text: convert.hex.rgb(semantic.text),
        popup_highlight: convert.hex.rgb(semantic.highlight),
        popup_text: convert.hex.rgb(semantic.text),
        popup: convert.hex.rgb(semantic.popup),
        side_panel_background: convert.hex.rgb(semantic.background),
        side_panel_border: convert.hex.rgb(semantic.border),
        side_panel_foreground: convert.hex.rgb(semantic.foreground),
        side_panel_separator: convert.hex.rgb(semantic.separator),
        tab_background_text: convert.hex.rgb(semantic.text),
        tab_loading: convert.hex.rgb(semantic.tab),
        tab_text: convert.hex.rgb(semantic.text),
        toolbar_button_icon: convert.hex.rgb(semantic.icon),
        toolbar_field_border_focus: convert.hex.rgb(semantic.border),
        toolbar_field_border: convert.hex.rgb(semantic.border),
        toolbar_field_focus: convert.hex.rgb(semantic.focus),
        toolbar_field_highlight_text: convert.hex.rgb(semantic.tetx),
        toolbar_field_highlight: convert.hex.rgb(semantic.highlight),
        toolbar_field_text_focus: convert.hex.rgb(semantic.text),
        toolbar_field_text: convert.hex.rgb(semantic.tetx),
        toolbar_field: convert.hex.rgb(semantic.field),
        toolbar_text: convert.hex.rgb(semantic.text),
        toolbar: convert.hex.rgb(semantic.toolbar),
    }
};
