// src/theme/debug.ts

import type { ThemeColors } from "../generated/theme-colors.js";
import { semantic } from "../semantic.js";

export const mapColors = {
	"editorGutter.addedSecondaryBackground": semantic.added,
	"editorGutter.background": semantic.background,
	"editorGutter.commentDraftGlyphForeground": semantic.foreground,
	"editorGutter.commentGlyphForeground": semantic.foreground,
	"editorGutter.commentRangeForeground": semantic.foreground,
	"editorGutter.commentUnresolvedGlyphForeground": semantic.foreground,
	"editorGutter.deletedBackground": semantic.deleted,
	"editorGutter.deletedSecondaryBackground": semantic.deleted,
	"editorGutter.foldingControlForeground": semantic.disabled,
	"editorGutter.itemBackground": semantic.info,
	"editorGutter.itemGlyphForeground": semantic.info,
	"editorGutter.modifiedBackground": semantic.modified,
	"editorGutter.modifiedSecondaryBackground": semantic.modified,
	"editorOverviewRuler.background": semantic.background,
	"editorOverviewRuler.border": semantic.zero,
	"editorOverviewRuler.bracketMatchForeground": semantic.match,
	"editorOverviewRuler.commentDraftForeground": semantic.syntax.comment,
	"editorOverviewRuler.commentForeground": semantic.syntax.comment,
	"editorOverviewRuler.commentUnresolvedForeground": semantic.syntax.comment,
	"editorOverviewRuler.commonContentForeground": semantic.foreground,
	"editorOverviewRuler.currentContentForeground": semantic.foreground,
	"editorOverviewRuler.deletedForeground": semantic.deleted,
	"editorOverviewRuler.errorForeground": semantic.error,
	"editorOverviewRuler.findMatchForeground": semantic.match,
	"editorOverviewRuler.incomingContentForeground": semantic.new,
	"editorOverviewRuler.infoForeground": semantic.info,
	"editorOverviewRuler.inlineChatInserted": semantic.added,
	"editorOverviewRuler.inlineChatRemoved": semantic.deleted,
	"editorOverviewRuler.modifiedForeground": semantic.modified,
	"editorOverviewRuler.rangeHighlightForeground": semantic.highlight,
	"editorOverviewRuler.selectionHighlightForeground": semantic.focus,
	"editorOverviewRuler.warningForeground": semantic.warning,
	"editorOverviewRuler.wordHighlightForeground": semantic.highlight,
	"editorOverviewRuler.wordHighlightStrongForeground": semantic.foregroundTransparent,
	"editorOverviewRuler.wordHighlightTextForeground": semantic.highlight,
	"minimap.chatEditHighlight": semantic.info,
	"minimap.infoHighlight": semantic.info,
	"minimap.selectionHighlight": semantic.highlight,
	"minimap.selectionOccurrenceHighlight": semantic.highlight,
	"minimap.warningHighlight": semantic.warning,
	"minimapGutter.addedBackground": semantic.added,
	"minimapGutter.deletedBackground": semantic.deleted,
	"minimapGutter.modifiedBackground": semantic.modified,
	"minimapSlider.activeBackground": semantic.active,
	"minimapSlider.background": semantic.slider,
	"minimapSlider.hoverBackground": semantic.hover,
	"editorMinimap.inlineChatInserted": semantic.added, // Minimap marker color for inline chat inserted content.
	"minimap.background": semantic.background,
	"diffEditorOverview.insertedForeground": semantic.added,
	"diffEditorOverview.removedForeground": semantic.deleted,
	"editorGutter.addedBackground": semantic.added,
	"editorOverviewRuler.addedForeground": semantic.added,
	"minimap.errorHighlight": semantic.error,
	"minimap.findMatchHighlight": semantic.highlight,
	"minimap.foregroundOpacity": semantic.hover,
	"scrollbar.background": semantic.background,
	"scrollbarSlider.background": semantic.slider,
	"scrollbarSlider.hoverBackground": semantic.hover,
} satisfies ThemeColors;
