// scripts/generate-theme-colors.ts

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const SOURCE_URL =
  "https://raw.githubusercontent.com/microsoft/vscode-docs/main/api/references/theme-color.md";

const OUTPUT_PATH = resolve(
  process.cwd(),
  "src/generated/theme-colors.ts",
);

type ThemeColor = {
  key: string;
  description: string;
};

function escapeJSDoc(text: string): string {
  return text
    .replaceAll("*/", "*\\/")
    .replace(/\s+/g, " ")
    .trim();
}

async function main(): Promise<void> {
  const response = await fetch(SOURCE_URL);

  if (!response.ok) {
    throw new Error(
      `Failed to download theme colors: ${response.status} ${response.statusText}`,
    );
  }

  const markdown = await response.text();

  /*
   * 公式ドキュメントの次の形式から
   * キーと説明文を抽出する:
   *
   * - `editor.background`: Editor background color.
   */
  const themeColorPattern =
    /^-\s+`([A-Za-z][A-Za-z0-9.-]*)`:\s*(.+)$/gm;

  const colors = new Map<string, string>();

  for (const match of markdown.matchAll(themeColorPattern)) {
    const key = match[1];
    const description = match[2].trim();

    colors.set(key, description);
  }

  const sortedColors: ThemeColor[] = [...colors.entries()]
    .map(([key, description]) => ({
      key,
      description,
    }))
    .sort((a, b) => a.key.localeCompare(b.key, "en"));

  if (sortedColors.length === 0) {
    throw new Error(
      "No theme colors were found. The source format may have changed.",
    );
  }

  const colorEntries = sortedColors
    .map(
      ({ key, description }) => `  {
    key: ${JSON.stringify(key)},
    description: ${JSON.stringify(description)},
  },`,
    )
    .join("\n");

  const interfaceEntries = sortedColors
    .map(
      ({ key, description }) => `  /** ${escapeJSDoc(description)} */
  ${JSON.stringify(key)}?: string;`,
    )
    .join("\n\n");

  const output = `\
/**
 * VS Code theme colors.
 *
 * Generated automatically from:
 * ${SOURCE_URL}
 *
 * Do not edit this file directly.
 */

export const themeColors = [
${colorEntries}
] as const;

export type ThemeColor =
  (typeof themeColors)[number];

export type ThemeColorKey =
  ThemeColor["key"];

/**
 * VS Code workbench theme colors.
 *
 * Property descriptions are taken from the official
 * VS Code theme color documentation.
 */
export interface ThemeColors {
${interfaceEntries}
}
`;

  await mkdir(dirname(OUTPUT_PATH), {
    recursive: true,
  });

  await writeFile(OUTPUT_PATH, output, "utf8");

  console.log(
    `Generated ${sortedColors.length} theme colors:`,
  );
  console.log(OUTPUT_PATH);
}

main().catch((error: unknown) => {
  console.error("Failed to generate theme colors.");

  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(error);
  }

  process.exitCode = 1;
});
