// scripts/generate-theme-colors.ts

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const SOURCE_URL =
  "https://raw.githubusercontent.com/microsoft/vscode-docs/main/api/references/theme-color.md";

const OUTPUT_PATH = resolve(
  process.cwd(),
  "src/generated/theme-colors.ts",
);

async function main(): Promise<void> {
  const response = await fetch(SOURCE_URL);

  if (!response.ok) {
    throw new Error(
      `Failed to download theme colors: ${response.status} ${response.statusText}`,
    );
  }

  const markdown = await response.text();

  /*
   * 公式ドキュメントの次の形式からキーを抽出する:
   *
   * - `editor.background`: Editor background color.
   */
  const themeColorPattern =
    /^-\s+`([A-Za-z][A-Za-z0-9.-]*)`:/gm;

  const keys = new Set<string>();

  for (const match of markdown.matchAll(themeColorPattern)) {
    keys.add(match[1]);
  }

  const sortedKeys = [...keys].sort((a, b) =>
    a.localeCompare(b, "en"),
  );

  if (sortedKeys.length === 0) {
    throw new Error(
      "No theme color keys were found. The source format may have changed.",
    );
  }

  const entries = sortedKeys
    .map((key) => `  ${JSON.stringify(key)},`)
    .join("\n");

  const output = `\
/**
 * VS Code theme color keys.
 *
 * Generated automatically from:
 * ${SOURCE_URL}
 *
 * Do not edit this file directly.
 */

export const themeColorKeys = [
${entries}
] as const;

export type ThemeColorKey =
  (typeof themeColorKeys)[number];

export type ThemeColors =
  Partial<Record<ThemeColorKey, string>>;
`;

  await mkdir(dirname(OUTPUT_PATH), {
    recursive: true,
  });

  await writeFile(OUTPUT_PATH, output, "utf8");

  console.log(
    `Generated ${sortedKeys.length} theme color keys:`,
  );
  console.log(OUTPUT_PATH);
}

main().catch((error: unknown) => {
  console.error("Failed to generate theme color keys.");

  if (error instanceof Error) {
    console.error(error.message);
  } else {
    console.error(error);
  }

  process.exitCode = 1;
});
