// semantic.ts

import { palette } from "./palette.js";
import { alpha } from "./color.js"

export const semantic = {
    zero: palette.fund.zero,
    accent: palette.light[14],
    active: palette.gray[19],
    added: alpha(palette.city.t, 0.5),
    background: palette.gray[2],
    breakpoint: palette.blue[7],
    border: palette.dark[15],
    deleted: alpha(palette.gray[7], 0.5),
    disabled: palette.gray[5],
    drop: palette.primary.background,
    error: palette.blue[5],
    focus: alpha(palette.gray[19], 0.1),
    foreground: palette.gray[18],
    highlight: palette.gray[5],
    hover: alpha(palette.gray[8], 0.3),
    inactive: palette.gray[10],
    info: palette.light[12],
    input: alpha(palette.gray[8], 0.4),
    link: palette.blue[17],
    local: palette.city.t,
    match: alpha(palette.blue[5], 0.3),
    modified: alpha(palette.light[16], 0.8),
    new: palette.city.t,
    old: palette.city.k,
    placeholder: palette.gray[3],
    remote: palette.city.k,
    shadow: alpha(palette.gray[4], 0.3),
    slider: alpha(palette.light[8], 0.3),
    sticky: alpha(palette.gray[10], 0.8),
    success: palette.blue[13],
    warning: palette.blue[8],
    widget: palette.blue[4],
    terminal: {
        background: palette.gray[2],
    },
    ansi: {
        black: palette.black,
        white: palette.white,
        blue: palette.city.k,
        cyan: palette.blue[10],
        green: palette.blue[11],
        magenta: palette.blue[12],
        red: palette.blue[13],
        yellow: palette.blue[14],
        brightBlack: palette.gray[7],
        brightWhite: palette.gray[2],
        brightBlue: palette.city.t,
        brightCyan: palette.light[10],
        brightGreen: palette.light[11],
        brightMagenta: palette.light[12],
        brightRed: palette.light[13],
        brightYellow: palette.light[14],
    },
    syntax: {
        comment: palette.blue[9],
        keyword: palette.light[15],
        string: palette.gray[19],
        function: palette.blue[13],
        variable: palette.primary.foreground,
        type: palette.light[15],
        constant: palette.blue[7],
        number: palette.blue[9],
    },
    order: palette.gray
} as const;
