// semantic.ts

import { palette } from "./palette.js";
import { alpha } from "./color.js"

export const semantic = {
    zero: palette.fund.zero,
    accent: palette.normal.magenta,
    active: palette.normal.white,
    added: alpha(palette.city.t, 0.5),
    background: palette.normal.black,
    breakpoint: palette.blue[7],
    border: palette.bright.black,
    deleted: alpha(palette.gray[7], 0.5),
    disabled: palette.gray[5],
    drop: palette.primary.background,
    error: palette.normal.red,
    focus: alpha(palette.gray[0], 0.1),
    foreground: palette.primary.foreground,
    highlight: palette.bright.black,
    hover: alpha(palette.normal.blue, 0.3),
    inactive: palette.gray[5],
    info: palette.normal.cyan,
    input: alpha(palette.gray[8], 0.4),
    link: palette.blue[17],
    local: palette.city.t,
    match: alpha(palette.blue[5], 0.3),
    modified: alpha(palette.bright.blue, 0.8),
    new: palette.city.t,
    old: palette.city.k,
    placeholder: palette.gray[3],
    remote: palette.city.k,
    shadow: alpha(palette.gray[4], 0.3),
    slider: alpha(palette.blue[8], 0.2),
    sticky: alpha(palette.gray[7], 0.9),
    success: palette.normal.green,
    warning: palette.normal.yellow,
    widget: palette.blue[4],
    terminal: {
        background: palette.primary.background,
    },
    ansi: {
        black: palette.normal.black,
        white: palette.normal.white,
        blue: palette.normal.blue,
        cyan: palette.normal.cyan,
        green: palette.normal.green,
        magenta: palette.normal.magenta,
        red: palette.normal.red,
        yellow: palette.normal.yellow,
        brightBlack: palette.bright.black,
        brightWhite: palette.bright.white,
        brightBlue: palette.bright.blue,
        brightCyan: palette.bright.cyan,
        brightGreen: palette.bright.green,
        brightMagenta: palette.bright.magenta,
        brightRed: palette.bright.red,
        brightYellow: palette.bright.yellow,
    },
    syntax: {
        comment: palette.blue[9],
        keyword: palette.normal.magenta,
        string: palette.bright.green,
        function: palette.bright.blue,
        variable: palette.primary.foreground,
        type: palette.bright.cyan,
        constant: palette.normal.yellow,
        number: palette.bright.green,
    },
    order: [
        palette.normal.blue,
        palette.normal.cyan,
        palette.normal.green,
        palette.normal.magenta,
        palette.normal.red,
        palette.normal.yellow,
        palette.bright.blue,
        palette.bright.cyan,
        palette.bright.green,
        palette.bright.magenta,
        palette.bright.red,
        palette.bright.yellow,
    ]
} as const;
