// semantic.ts

import { palette } from "./palette.js";
import { alpha } from "./color.js"

export const semantic = {
    zero: palette.fund.zero,
    accent: palette.normal.magenta,
    active: palette.normal.white,
    added: alpha(palette.city.t, 0.3),
    background: palette.normal.black,
    border: palette.bright.black,
    deleted: alpha(palette.gray[7], 0.5),
    disabled: palette.gray[5],
    error: palette.normal.red,
    focus: alpha(palette.gray[0], 0.1),
    foreground: palette.primary.foreground,
    hover: alpha(palette.normal.blue, 0.3),
    inactive: palette.gray[5],
    info: palette.normal.cyan,
    link: palette.bright.blue,
    modified: palette.bright.blue,
    new: palette.city.t,
    old: palette.city.k,
    success: palette.normal.green,
    warning: palette.normal.yellow,
    terminal: {
        background: palette.primary.background,
    },
    ansi: {
        black: palette.normal.black,
        white: palette.normal.white,
        blue: palette.normal.blue,
        cyan: palette.normal.cyan,
        green: palette.normal.green,
        magenta: palette.normal.magenta,
        red: palette.normal.red,
        yellow: palette.normal.yellow,
        brightBlack: palette.bright.black,
        brightWhite: palette.bright.white,
        brightBlue: palette.bright.blue,
        brightCyan: palette.bright.cyan,
        brightGreen: palette.bright.green,
        brightMagenta: palette.bright.magenta,
        brightRed: palette.bright.red,
        brightYellow: palette.bright.yellow,
    },
    syntax: {
        comment: palette.bright.black,
        keyword: palette.normal.magenta,
        string: palette.bright.green,
        function: palette.bright.blue,
        variable: palette.primary.foreground,
        type: palette.bright.cyan,
        constant: palette.normal.yellow,
    },
    order: [
        palette.normal.blue,
        palette.normal.cyan,
        palette.normal.green,
        palette.normal.magenta,
        palette.normal.red,
        palette.normal.yellow,
        palette.bright.blue,
        palette.bright.cyan,
        palette.bright.green,
        palette.bright.magenta,
        palette.bright.red,
        palette.bright.yellow,
    ]
} as const;
